config/routes.rb
Rails.application.routes.draw do
  
  get 'about/index'

  resources "contacts", only: [:new, :create]

  post 'notification', to: 'notification#create'

  get 'order/new'

  post 'order/create'

  get 'order/index'

  resources :products
  resources :businesses
  
  root 'home#home'
  # root 'contacts#new'

  get 'map' => 'home#map', as: 'map'
  get 'json-map' => 'home#json_map', as: 'json-map'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # sessions
  resources :sessions, only: %i[new create destroy]
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: %i[show edit update destroy]
  respond_to :html, :json

  def index
    @businesses = Business.all
    respond_with @businesses
  end

  def show
  end

  def new
    @business = Business.new
    respond_with @business
  end

  def edit
  end

  def create
    @business = Business.new(business_params)
    @user = User.find(session[:id])
    flash[:notice] = 'Seu negócio foi criado!' if @business.save
    @user.business = @business
    @user.save
    redirect to users_path
    # respond_with @business
  end

  def update
    flash[:notice] = 'Negócio atualizado' if @business.update(business_params)
    redirect_to users_path
    # respond_with @business
  end

  def destroy
    @business.destroy
    flash[:notice] = 'Negócio apagado!' if @business.destroy
    redirect_to users_path
    # respond_with @business
  end

  private

    def set_business
      @business = Business.find(params[:id])
    end

    def business_params
      params.require(:business).permit(:business_name, :business_info, :business_time, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, :business_phone, :business_street, :business_number, :business_neighbor, :business_city, :business_state, :latitude, :longitude, :active)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(business) do |f| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h3>Dados Cadastrais:</h3>

  <div class="field">
    <%= f.label :business_name %>
    <%= f.text_field :business_name %>
  </div>
  
  <div class="field">
    <%= f.label :active %>
    
  </div>
  <%= f.check_box :active %>

  <div class="field">
    <%= f.label :business_phone %>
    <%= f.text_field :business_phone %>
  </div>

  <div class="field">
    <%= f.label :business_info %>
    <%= f.text_area :business_info %>
  </div>

  <div class="field">
    <%= f.label :business_time %>
    <%= f.text_field :business_time %>
  </div>

<h3>Cardápio da Semana</h3>

  <div class="field">
    <%= f.label :monday, 'Segunda' %>
    <%= f.text_field :monday %>
  </div>
  <div class="field">
    <%= f.label :tuesday, 'Terça' %>
    <%= f.text_field :tuesday %>
  </div>
  <div class="field">
    <%= f.label :wednesday, 'Quarta' %>
    <%= f.text_field :wednesday %>
  </div>
  <div class="field">
    <%= f.label :thursday, 'Quinta' %>
    <%= f.text_field :thursday %>
  </div>
  <div class="field">
    <%= f.label :friday, 'Sexta' %>
    <%= f.text_field :friday %>
  </div>
  <div class="field">
    <%= f.label :saturday, 'Sábado' %>
    <%= f.text_field :saturday %>
  </div>
  <div class="field">
    <%= f.label :sunday, 'Domingo' %>
    <%= f.text_field :sunday %>
  </div>


<h3>Localização:</h3>
  <div class="field">
    <%= f.label :business_street %>
    <%= f.text_field :business_street %>
  </div>

  <div class="field">
    <%= f.label :business_number %>
    <%= f.text_field :business_number %>
  </div>

  <div class="field">
    <%= f.label :business_neighbor %>
    <%= f.text_field :business_neighbor %>
  </div>

  <div class="field">
    <%= f.label :business_city %>
    <%= f.text_field :business_city %>
  </div>

  <div class="field">
    <%= f.label :business_state %>
    <%= f.text_field :business_state %>
  </div>


  <div class="actions">
    <%= f.submit 'Salvar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<div class="container">
  <h1>Editando meu negócio</h1>

  <%= render 'form', business: @business %>
	<br>
  <%= link_to 'Voltar', users_path, class: 'btn btn-primary' %>
</div>

app/views/businesses/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Businesses</h1>

  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Sobre</th>
        <th>Atendimento</th>
        <th>Rua</th>
        <th>Número</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th>Responsável</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @businesses.each do |business| %>
        <tr>
          <td><%= business.business_name %></td>
          <td><%= business.business_info %></td>
          <td><%= business.business_time %></td>
          <td><%= business.business_street %></td>
          <td><%= business.business_number %></td>
          <td><%= business.business_neighbor %></td>
          <td><%= business.business_city %></td>
          <td><%= business.business_state %></td>
          <td><%= business.user.name %></td>
          <td><%= link_to 'Ver', business %></td>
          <td><%= link_to 'Editar', edit_business_path(business) %></td>
          <td><%= link_to 'Deletar', business, method: :delete, data: { confirm: 'Tem certeza' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Business', new_business_path %>
</div>

app/views/businesses/new.html.erb
<div class="container">
  <h1>Meu negócio:</h1>

  <%= render 'form', business: @business %>

  <br>

  <%= link_to 'Voltar', users_path, class: 'btn btn-primary' %>
</div>

app/views/businesses/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Meu negócio:</strong>
    <%= @business.business_name %>
  </p>

  <p>
    <strong>O que oferecemos:</strong>
    <%= @business.business_info %>
  </p>

  <p>
    <strong>Horário de atendimento:</strong>
    <%= @business.business_time %>
  </p>

  <p>
    <strong>Rua:</strong>
    <%= @business.business_street %>
  </p>

  <p>
    <strong>Número:</strong>
    <%= @business.business_number %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= @business.business_neighbor %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= @business.business_city %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= @business.business_state %>
  </p>

  <p>
    <strong>Responsável:</strong>
    <%= @business.user.name %>
  </p>

  <%= link_to 'Editar', edit_business_path(@business) %> |
  <%= link_to 'Voltar', businesses_path %>
</div>