config/routes.rb
Rails.application.routes.draw do
  
  get 'about/index'

  resources "contacts", only: [:new, :create]

  post 'notification', to: 'notification#create'

  get 'order/new'

  post 'order/create'

  get 'order/index'

  resources :products
  resources :businesses
  
  root 'home#home'
  # root 'contacts#new'

  get 'map' => 'home#map', as: 'map'
  get 'json-map' => 'home#json_map', as: 'json-map'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # sessions
  resources :sessions, only: %i[new create destroy]
end

app/models/user.rb
# Model for the user
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  has_one :business, dependent: :destroy
  validates :name, :email, presence: true

  def self.auth(email, password)
    user = User.where(email: email).first
    user && user.authenticate(password) ? user : nil
  end
end

app/controllers/users_controller.rb
class UsersController < LoggedController
  before_action :set_user, only: %i[show edit update destroy]
  respond_to :html, :json

  def index
    @users = User.all
    respond_with @users
  end

  def show
  end

  def new
    @user = User.new
    respond_with @user
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    flash[:notice] = 'Usuário Criado! Agora acesse sua conta!' if @user.save
    
    redirect_to new_session_path
  end

  def update
    flash[:notice] = 'Usuário atualizado' if @user.update(user_params)
    respond_with @user
  end

  def destroy
    @user.destroy
    flash[:notice] = 'Usuário apagado!' if @user.destroy
    respond_with @user
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :password_digest)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "erro") %> Não foi possível salvar!:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email, 'E-mail' %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password, 'Senha' %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, 'Confirme a Senha' %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit 'Cadastrar', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h3>Edite seu cadastro</h3>
  <%= render 'form', user: @user %>
	<br>

  <%= link_to 'Voltar', users_path, class: 'btn btn-primary' %>

</div>

app/views/users/index.html.erb
<div class="container card-wrapper">

  <div class="row">
    <div class="col s12 m3">
      <div class="card">
        <div class="card-image">
          <%= image_tag("profile_icon.svg", :alt => "Meu perfil") %>
          <span class="card-title">Meu Perfil</span>
        </div>
        <div class="card-content">
          <p>Aqui é o lugar para você dar manutenção no seu perfil, como alterar dados, trocar senha,
            emails, e coisas asism! É importante que estes dados estejam sempre atualizados!</p>
        </div>
        <div class="card-action">
          <%=link_to 'Meu Perfil', edit_user_path(current_user), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>

    <div class="col s12 m3">
      <div class="card">
        <div class="card-image">
          <%= image_tag("business_icon.svg", :alt => "Meu negocio") %>
          <span class="card-title">Meu Negócio</span>
        </div>
        <div class="card-content">
          <p>Aqui é onde você vai criar ou editar seu negócio! Esta parte merece uma atenção toda especial,
            pois os dados auqi informados serão exibidos pelo Aplicativo! Capriche!</p>
        </div>
        <div class="card-action">
          <% if current_user.business.present? %>
            <%= link_to 'Meu Negócio', edit_business_path(current_user.business.id), class: 'btn btn-primary' %>
          <% else %>
            <%= link_to 'Meu Negócio', new_business_path, class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  
    <div class="col s12 m3">
      <div class="card">
        <div class="card-image">
          <%= image_tag("pagamento.svg", :alt => "Meu perfil") %>
          <span class="card-title">Pagamentos</span>
        </div>
        <div class="card-content">
          <p>Aqui é onde você realiza pagamentos e controle os pagamentos já realizados! Quando o pagamento estiver vencendo, você é notificado por e-mail ou mensagem!</p>
        </div>
        <div class="card-action">
          <%= link_to 'Pagamento', order_new_path(product_id: '1'), :"data-turbolinks" => false, class: 'btn btn-primary disabled' %>
        </div>
      </div>
    </div>

    <div class="col s12 m3">
      <div class="card">
        <div class="card-image">
          <%= image_tag("invoice.svg", :alt => "Meu perfil") %>
          <span class="card-title">Ordens</span>
        </div>
        <div class="card-content">
          <p>Aqui é onde você encontra o histórico de suas compras. Todas as suas ordens de compra ficam aqui, com data de criação, data de vencimento e status do seu negócio!</p>
        </div>
        <div class="card-action">
          <%= link_to 'Ordens', order_index_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>

  </div>


    

app/views/users/new.html.erb
<div class="container">
	<div class="animated fadeInRight">
	  <h1>Cadastro</h1>
	  <h4>Que bom que está aqui! Vem com a gente!</h4>
	  <br>
		
	  <%= render 'form', user: @user %>
	  
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Nome:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>E-mail:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>Senha</strong>
    **********
  </p>

  <%= link_to 'Editar', edit_user_path(@user) %> |
  <%= link_to 'Voltar', users_path %>
</div>