config/routes.rb
Rails.application.routes.draw do
  
  get 'about/index'

  resources "contacts", only: [:new, :create]

  post 'notification', to: 'notification#create'

  get 'order/new'

  post 'order/create'

  get 'order/index'

  resources :products
  resources :businesses
  
  root 'home#home'
  # root 'contacts#new'

  get 'map' => 'home#map', as: 'map'
  get 'json-map' => 'home#json_map', as: 'json-map'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # sessions
  resources :sessions, only: %i[new create destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def map
    if params[:search].present?
      @result = Business.near(params[:search], 3, units: :km)
      @businesses = @result.where('active = ?', true)
      # render :json => @businesses
    else
      # @businesses = Business.near('Praça da Matriz, Mirassol', 2, units: :km)
      redirect_to root_path
    end
    
    @hash = Gmaps4rails.build_markers(@businesses) do |business, marker|
      marker.lat business.latitude
      marker.lng business.longitude
      marker.picture({ url: ActionController::Base.helpers.asset_path("restaurant.png"), width: 32, height: 32 })
      marker.title gmaps4rails_title(business.business_name)
      marker.infowindow gmaps4rails_infowindow(business)  
    end
  end

  def json_map
    @businesses = Business.near(params[:search], 2, units: :km)
    render :json => @businesses
  end

  def gmaps4rails_title(business)
    "#{business}"
  end

  def gmaps4rails_infowindow(business)
    "<div id=\"iw-container\"><div class=\"iw-title\">#{business.business_name}</div> <br><br> <em>#{business.business_info}</em> <hr> <p>Funcionamento: #{business.business_time} </p> <hr> <p>Telefone: #{business.business_phone} </p> <hr> <p>#{business.address}</p></div>"
  end

  def home

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <%= link_to (image_tag 'small_logo.png', class: 'responsive-img'), root_path %>          
          <p class="grey-text text-lighten-4 slogan">A maneira de fácil de encontrar comida.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Vem com a gente!</h5>
          <ul>
            <li><%= link_to 'Entrar', new_session_path, class: "grey-text text-lighten-3" %></li>
            <li><%= link_to 'Cadastrar', new_user_path, class: "grey-text text-lighten-3" %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container center">
      © 2017 Copyright by FFW Design | Mirassol | SP
      <!-- <a class="grey-text text-lighten-4 right" href="#!">More Links</a> -->
      </div>
    </div>
  </footer>

app/views/home/_search.html.erb
<% unless session[:id].present? %>
  <div class="container">

      <section id="search">
        <%= form_tag map_path, :method => :get do %>
      <div class="row">
        <div class="input-field col s12 m10">
          <i class="material-icons prefix">location_on</i>
          <%= label :search, 'Coloque um endereço para encontrar comida' %>
          <%= text_field_tag :search, params[:search] %>
        </div>
        <div class="col s12 m4">
            <%= submit_tag "Por perto", :name => nil, class: "waves-effect waves-orange btn" %>
        </div>
      </div>
    <% end %>
      </section>
  </div>
<% end %>

app/views/home/home.html.erb
<div class="animated fadeInRight">
  <%= render 'search' %>
</div>
<div class="parallax-container">
  <div class="caption center-align">
    <h1 class="animated bounceInDown">Marmiteco</h1>
    <h3 class="light grey-text text-lighten-3 animated bounceInLeft" >Pensou em comida?</h3>
    <h3 class="light grey-text text-lighten-3 animated bounceInRight" >Encontramos para você!</h3>
  </div>
  <div class="parallax"><%= image_tag 'bg03.jpg' %> </div>
</div>
<div class="container">
  <section class="section01">
  <div class="row">
    <div class="wraper01 animated " id="section01">
      <div class="col s12 m4">
        <%= image_tag 'phone-map.png', class: 'responsive-img' %>
      </div>
    </div>
    <div class="wraper02 animated " id="section02">
      <div class="col s12 m6 offset-m2">
        <h4>Onde comer?</h4>
        <em>
          Aqui você encontra o melhor lugar para comer! Comida sempre fresquinha e pertinho de você!
        </em>
        <p>
          Basta baixar o nosso aplicativo, que você sempre terá um bom lugar para comer!
        </p>
        <p>Através de um avançado recurso de Geolocalizaçào, não importa onde esteja, sempre tem comida por perto!</p>
      </div>
    </div>
    </div>
  </section>
  
  <hr>

  <section class="section02">
  <div class="row">
    <div class="wraper03 animated" id="section03">
      <div class="col m4 s12">
        
        <h4>Você vende comida?</h4>
        <em>
          Aqui também é o melhor lugar para estar sempre a vista dos consumidores!
        </em>
        <p>
          Fazendo parte da nossa comunidade, você será sempre uma opção para os consumidaores mais conectados!
        </p>
        <p>Com uma pequena mensalidade, você cria a página do seu negócio e imediatamente está disponível em nosso aplicativo, aparecendo para quem fizer a busca num raio de 2km. Dessa forma, fica mais fácil ser encontrado por quem procura comida!</p>
      </div>
    </div>
    <div class="wraper04 animated"  id="section04">
      <div class="col m6 offset-m2 s12">
        <%= image_tag 'choosing.png', class: 'responsive-img' %>
      </div>
    </div>
    </div>
  </section>


  <div class="row">
    <div class="col s12 m4">
      <div class="card blue-grey darken-1 my-card animated" id="my-card">
            <div class="card-content white-text">
              <span class="card-title">Encontre onde comer</span>
              <p>Basta colocar um endereço no campo acima e vai encontrar lugares que serve comida, seja de forma expressa como restaurantes. O jeito mais fácil de encontrar onde comer!</p>
            </div>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="card blue-grey darken-1 my-card animated" id="my-card02">
            <div class="card-content white-text">
              <span class="card-title">Para quem vende</span>
              <p>Se você vende comida, seja rsetaurante ou entrega de marmitas, este negócio é para você! De maneira simples seu negócio é colocado no app Marmiteco, sendo assim facilmente encontrado! .</p>
            </div>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="card blue-grey darken-1 my-card animated" id="my-card03">
            <div class="card-content white-text">
              <span class="card-title">Para quem tem fome</span>
              <p>Basta colocar um endereço no site ou utilizar nosso aplicativo para encontrar facilmente onde comer! Encontramos lugares ao seu redor, com resenha e telefone para contato.</p>
            </div>

      </div>
    </div>
  </div>
  </div>  

  <%= render 'footer' %>

</div>

app/views/home/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyDjvesALGyVilgLBhIcviPN7MaZYgnpL34"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<div class="map-container">
  <div id="map"></div>
</div>


<script>
  handler = Gmaps.build("Google");
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(15)

  })
</script>

app/views/home/map.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyDjvesALGyVilgLBhIcviPN7MaZYgnpL34"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<%= render 'search' %>

<div class="map-container col s12 active">
  <div id="map"></div>
</div>


<script>
  handler = Gmaps.build("Google");
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(15)

  })
</script>