config/routes.rb
Rails.application.routes.draw do
  
  get 'about/index'

  resources "contacts", only: [:new, :create]

  post 'notification', to: 'notification#create'

  get 'order/new'

  post 'order/create'

  get 'order/index'

  resources :products
  resources :businesses
  
  root 'home#home'
  # root 'contacts#new'

  get 'map' => 'home#map', as: 'map'
  get 'json-map' => 'home#json_map', as: 'json-map'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # sessions
  resources :sessions, only: %i[new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode, :reverse_geocode
  
  belongs_to :user

  validates :business_name, presence: true, length: { maximum: 150 }
  validates :business_info, presence: true, length: { maximum: 450 }
  validates :business_time, presence: true, length: { maximum: 150 }
  validates :business_street, presence: true, length: { maximum: 150 }
  validates :business_number, presence: true, length: { maximum: 30 }
 validates :business_neighbor, presence: true, length: { maximum: 50 }
  validates :business_city, presence: true, length: { maximum: 100 }
  validates :business_state, presence: true, length: { maximum: 2 }
  validates :business_phone, presence: true



  def address
    "#{business_street}, #{business_number}, #{business_neighbor}, #{business_city}, #{business_state}"
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone,     :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "[MARMITECO] - Tenho Interesse!",
      :to => "mirassol.code@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
end

app/models/user.rb
# Model for the user
class User < ApplicationRecord
  has_secure_password
  has_many :orders
  has_one :business, dependent: :destroy
  validates :name, :email, presence: true

  def self.auth(email, password)
    user = User.where(email: email).first
    user && user.authenticate(password) ? user : nil
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def map
    if params[:search].present?
      @result = Business.near(params[:search], 3, units: :km)
      @businesses = @result.where('active = ?', true)
      # render :json => @businesses
    else
      # @businesses = Business.near('Praça da Matriz, Mirassol', 2, units: :km)
      redirect_to root_path
    end
    
    @hash = Gmaps4rails.build_markers(@businesses) do |business, marker|
      marker.lat business.latitude
      marker.lng business.longitude
      marker.picture({ url: ActionController::Base.helpers.asset_path("restaurant.png"), width: 32, height: 32 })
      marker.title gmaps4rails_title(business.business_name)
      marker.infowindow gmaps4rails_infowindow(business)  
    end
  end

  def json_map
    @businesses = Business.near(params[:search], 2, units: :km)
    render :json => @businesses
  end

  def gmaps4rails_title(business)
    "#{business}"
  end

  def gmaps4rails_infowindow(business)
    "<div id=\"iw-container\"><div class=\"iw-title\">#{business.business_name}</div> <br><br> <em>#{business.business_info}</em> <hr> <p>Funcionamento: #{business.business_time} </p> <hr> <p>Telefone: #{business.business_phone} </p> <hr> <p>#{business.address}</p></div>"
  end

  def home

  end
end

app/controllers/order_controller.rb
class OrderController < LoggedController
  before_action :set_user, :set_order, :set_product, :set_reference

  protect_from_forgery

  # Gerar um Token de sessão para nosso pagamento
  def new
    @product
    session = PagSeguro::Session.new
    @session_id = session.create.id
  end

  # Enviar nosso pagamento para o Pagseguro
  def create

    payment = PagSeguro::Payment.new(notification_url: 'https://safe-dusk-38202.herokuapp.com/notification', payment_method: 'creditCard', reference: '1')


    ## Adicionando endereço do comprador
    address = PagSeguro::Address.new(postal_code: params[:zipcode], street: params[:street], number: params[:number], complement: '', district: params[:district], city: params[:city], state: params[:state])
    
    shipping = PagSeguro::Shipping.new
    shipping.address = address
    payment.shipping = shipping
    

    items = [PagSeguro::Item.new(id: @product.id, description: @product.description, amount: @product.price, quantity: 1)]
    payment.items = items

    # Criando uma referencia para a nossa ORDER
    
    payment.reference = @reference


    phone = PagSeguro::Phone.new(params[:phone_code], params[:phone_number])
    document = PagSeguro::Document.new(params[:cpf])
    sender = PagSeguro::Sender.new(email: params[:email], name: params[:name], hash_id: params[:sender_hash] )
    sender.phone = phone
    sender.document = document
    payment.sender = sender

    # payment.credit_card_token = params[:card_token]
    credit_card = PagSeguro::CreditCard.new(params[:card_token])
    credit_card.holder = PagSeguro::Holder.new(params[:card_name], params[:birthday].to_datetime())
    document = PagSeguro::Document.new(params[:cpf])
    credit_card.holder.document = document
    phone = PagSeguro::Phone.new(params[:phone_code], params[:phone_number])
    credit_card.holder.phone = phone
    
    credit_card.billing_address = address

    payment.credit_card = credit_card


    credit_card.installment = PagSeguro::Installment.new(1, @product.price)

    # payment.create
    transaction = payment.transaction



    # Cria uma Order para registro das transações
    
    create_order
    
    
    

    if payment.errors.any?
     puts "=> ERRORS"
     puts payment.errors.join("\n")
     render plain: "Erro No Pagamento #{payment.errors.join("\n")}"
    else

      redirect_to order_index_path

    end

  end

  def index
    @user
    @orders
  end

private
  
  def set_user
    @user = User.find(session[:id])
  end
  def set_order
    @orders = @user.orders.order('created_at DESC')
  end
  def set_product
    @product = Product.last
  end
  def set_reference
    @reference = "REF_#{(0...8).map { (65 + rand(26)).chr }.join}_#{@product.id}"
  end
def create_order
  Order.create(product_id: @product.id, price: @product.price, buyer_name: @user.name, reference: @reference, status: 'Pendente', user_id: @user.id)
  @order = Order.last
  @order.user.business.active = false
  @order.user.business.save!
end


end

app/controllers/users_controller.rb
class UsersController < LoggedController
  before_action :set_user, only: %i[show edit update destroy]
  respond_to :html, :json

  def index
    @users = User.all
    respond_with @users
  end

  def show
  end

  def new
    @user = User.new
    respond_with @user
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    flash[:notice] = 'Usuário Criado! Agora acesse sua conta!' if @user.save
    
    redirect_to new_session_path
  end

  def update
    flash[:notice] = 'Usuário atualizado' if @user.update(user_params)
    respond_with @user
  end

  def destroy
    @user.destroy
    flash[:notice] = 'Usuário apagado!' if @user.destroy
    respond_with @user
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :password_digest)
    end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    User.find(session[:id])
  end

end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">Entrar</a></li>
  <li><a href="#!">Cadastrar</a></li>
  <li><%= link_to('Sair', session_path(1), method: :delete) %></li>
</ul>

<nav>
   <div class="nav-wrapper">
     <a href="#" class="brand-logo">Logo</a>
     <ul id="nav-mobile" class="right hide-on-med-and-down">
       <li><%= link_to 'Home', root_path %></li>
       <li><%= link_to 'Sobre nós', '#' %></li>
       <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Usuário<i class="material-icons right">arrow_drop_down</i></a></li>
     </ul>
   </div>
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marmiteco</title>
    <%= Gon::Base.render_data %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
  <% if notice %>
    <div id="notice-wrapper">
      <p class='notice'><%= notice %></p>
    </div>
  <% end %>
  
    <ul id="slide-out" class="side-nav">
      <li><div class="user-view">
        <div class="background">
          <%= link_to (image_tag 'small_logo.png'),'#' , class: 'side-logo' %>
        </div>
          
          
      </div></li>
      <% if session[:id].present? %>
        <li><%= link_to('Sair', session_path(1), method: :delete) %></li>
      <% else %>
        <li><%= link_to 'Entrar', new_session_path %></li>
        <li><div class="divider"></div></li>
        <li><%= link_to 'Cadastrar', new_user_path %></li>
        <li><div class="divider"></div></li>
        <li><%= link_to 'Como Funciona?', about_index_path %></li>
      <% end %>

    </ul>
    <a href="#" data-activates="slide-out" class="button-collapse hide-on-med-and-up"><i class="material-icons">menu</i></a>
        
    <nav>
       <div class="nav-wrapper">
         <%= link_to (image_tag 'small_logo.png'), root_path, { :"data-turbolinks" => false, class: "brand-logo" } %>
         <ul id="nav-mobile" class="right hide-on-med-and-down">
           <% if session[:id].present? %>
              <% if current_user.orders.last.end_date > Date.today + 10.days %>
                <li class="light_green"> </li>
              <% elsif current_user.orders.last.end_date < Date.today + 10.days && current_user.orders.last.end_date >= Date.today %>
                <li class="light_yellow"> </li>
              <% elsif current_user.orders.last.end_date < Date.today %>
                <%= current_user.business.active = false %>
                <% current_user.business.save %>
                <li class="light_red"> </li>
              <% end %>
              
              <li><%= link_to 'Dashboard', users_path %></li>
              <li><h4>Olá, <%= current_user.name %>!</h4></li>
              <li><li><%= link_to('Sair', session_path(1), method: :delete) %></li></li>
          <% else %>
              <li><%= link_to 'Marmiteco', root_path, :"data-turbolinks" => false %></li>
              <li><%= link_to 'Como funciona?', about_index_path, :"data-turbolinks" => false %></li>
              <li><%= link_to 'Entrar', new_session_path %></li>
              <li><%= link_to 'Cadastrar', new_user_path %></li>
           <% end %>
         </ul>
       </div>
     </nav>
     <br>
    <%= yield %>

    <script>
      $( document ).ready(function() {
          setTimeout(function() {
            $('#notice-wrapper').fadeOut("slow", function() {
              $(this).remove();
            })
          }, 3000);
        });
   </script>
   <script type="text/javascript" src="https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"></script>

  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marmiteco</title>
    <%= Gon::Base.render_data %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
  <% if notice %>
    <div id="notice-wrapper">
      <p class='notice'><%= notice %></p>
    </div>
  <% end %>
  
    <ul id="slide-out" class="side-nav">
      <li>Bem-vindo! <br> Logo entraremos em contato!</li>

<!--       <li><div class="user-view">
        <div class="background">
          <%= link_to (image_tag 'small_logo.png'),'#' , class: 'side-logo' %>
        </div>
          
          
      </div></li>
      <% if session[:id].present? %>
        <li><%= link_to('Sair', session_path(1), method: :delete) %></li>
      <% else %>
        <li><%= link_to 'Entrar', new_session_path %></li>
        <li><div class="divider"></div></li>
        <li><%= link_to 'Cadastrar', new_user_path %></li>
        <li><div class="divider"></div></li>
        <li><%= link_to 'Como Funciona?', about_index_path %></li>
      <% end %> -->

    </ul>
    <a href="#" data-activates="slide-out" class="button-collapse hide-on-med-and-up"><i class="material-icons">menu</i></a>
        
    <nav>
       <div class="nav-wrapper">
         <%= link_to (image_tag 'small_logo.png'), root_path, { :"data-turbolinks" => false, class: "brand-logo" } %>
         <!-- <ul id="nav-mobile" class="right hide-on-med-and-down">
           <% if session[:id].present? %>
              <li><%= link_to 'Dashboard', users_path %></li>
              <li><h4>Olá, <%= current_user.name %>!</h4></li>
              <li><li><%= link_to('Sair', session_path(1), method: :delete) %></li></li>
          <% else %>
              <li><%= link_to 'Marmiteco', root_path, :"data-turbolinks" => false %></li>
              <li><%= link_to 'Como funciona?', about_index_path, :"data-turbolinks" => false %></li>
              <li><%= link_to 'Entrar', new_session_path %></li>
              <li><%= link_to 'Cadastrar', new_user_path %></li>
           <% end %>
         </ul> -->
       </div>
     </nav>
     <br>
    <%= yield %>

    <script>
      $( document ).ready(function() {
          setTimeout(function() {
            $('#notice-wrapper').fadeOut("slow", function() {
              $(this).remove();
            })
          }, 3000);
        });
   </script>

  </body>
</html>